### ISSUE TITLE
Change custom database table name prefix

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/Dnn.StructuredContent#46]
Currently, the custom table name prefix is `zz_`.  It has been agreed this should be `sc_` instead.

**Comment by X3Technology** [comment]
might be safer to use "dnnsc_" or "dnn_sc_"

**Comment by david-poindexter** [comment]
Per our offline conversation, we decided to go with `StructuredContent_ContentType_`.  This brings more clarity and avoids potential confusion.

**Comment by WillStrohl** [comment]
Please see PR #63 that may require additional work.  The objectQualifiers on the object names wasn't correctly applied to the installation SQL script.
