### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/Dnn.StructuredContent#5]
@mathisjay I cloned the repository and tried to run a build, I noticed the references to DNN libraries are relative instead of using nuget packages and did not find a manifest or any special build scripts. I can help with that but would need to make a build succeed first. So 2 questions:

- Currently into which folder of a DNN site do you put this in order to be able to build it ?
- Are you OK targeting DNN 9.10.x instead of 9.2.x ? This would allow much better usage of Dependency Injection and I don't think we want to support older versions of DNN right ?

**Comment by X3Technology** [comment]
Since this is (currently) a PersonaBar module, I have it in: \DesktopModules\Admin\Dnn.PersonaBar\Modules\Dnn.StructuredContent

Fine with moving 9.10.  Wow.  9.2!  Just goes to show how long ago I started this :)

**Comment by david-poindexter** [comment]
I was able to get this far, but so far there appear to be no SQL scripts to create the DB objects.

![image](https://user-images.githubusercontent.com/4568451/133871711-ec1a2989-7965-4068-bf00-9e157da99453.png)

I was able to add the LINQ to SQL tools to VS 2019 and now the DBML visualizer works.

![image](https://user-images.githubusercontent.com/4568451/133871723-81d7f35c-fe87-4ed1-ba9a-751f4ad422d4.png)

**Comment by X3Technology** [comment]
I will create a SQL script for all the tables and the necessary default data

**Comment by WillStrohl** [comment]
Also updated in #63 and #64
