### ISSUE TITLE
Database Schema Discussion for `ID`

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.StructuredContent#65]
I've noticed that the `ID` columns are literally named 'ID`.  This issue is here to discuss if we want to change that before this module has an official release to prevent potential issues in the future since this is a reserved word.

**Comment by WillStrohl** [comment]
@david-poindexter @valadas FYI...

**Comment by valadas** [comment]
Can you define what you mean by Id being a reserved word? 

I always use Id because then you can have a base class for your entities and do generic stuff that works with any entity

**Comment by WillStrohl** [comment]
D'oh!  Never mind.  Got my SQL crossed.  ID is okay.  :)  

https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15

**Comment by WillStrohl** [comment]
However, a more specific ID naming convention is often better/easier and less error-prone when more complex queries are needed to be made.

**Comment by donker** [comment]
Yep. My pattern follows the rest of DNN where we use WidgetId to reference the ID of a Widget. I agree we should attempt to ensure we make a good start with this module.
